services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: auraface-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Asia/Taipei
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "0.0.0.0:5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: auraface-nginx
    ports:
      - "443:443"
      - "7862:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - auraface
    restart: unless-stopped

  auraface:
    build: .
    container_name: auraface-app
    env_file:
      - .env
    ports:
      - "7860:7860"
      - "7861:7861"
      - "7859:7859"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PYTHONPATH=${PYTHONPATH}
      - WEBSOCKET_PORT=${WEBSOCKET_PORT}
      - NVIDIA_VISIBLE_DEVICES=all
      - PYTHONUNBUFFERED=1
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    restart: unless-stopped
    command: sh -c "python3 websocket_realtime.py & python3 app.py"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  postgres_data:
