services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: auraface-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "0.0.0.0:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auraface"]
      interval: 5s
      timeout: 5s
      retries: 5

  auraface:
    build: .
    container_name: auraface-app
    ports:
      - "0.0.0.0:7860:7860"
      - "0.0.0.0:7861:7861"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PYTHONPATH=${PYTHONPATH}
      - WEBSOCKET_PORT=${WEBSOCKET_PORT}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    restart: unless-stopped
    command: sh -c "python3 websocket_realtime.py & python3 app.py"

volumes:
  postgres_data: